#!/usr/bin/env node
// Emits the Tuya credentials into every project that needs them, so there is
// one place to edit instead of four copies that drift.
//
// Values come from the environment first (that is how EAS supplies them, since
// secrets.json is untracked and never reaches a build server), otherwise from
// home-control/secrets.json. When neither is present the files are still
// written, with empty values: the app already degrades to "AC control is not
// configured" rather than failing to build.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const homeControl = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(homeControl, '..');

const FIELDS = [
  ['clientId', 'ROOM_TUYA_CLIENT_ID'],
  ['clientSecret', 'ROOM_TUYA_CLIENT_SECRET'],
  ['apiBaseUrl', 'ROOM_TUYA_API_BASE_URL'],
  ['infraredId', 'ROOM_TUYA_INFRARED_ID'],
  ['acRemoteId', 'ROOM_TUYA_AC_REMOTE_ID'],
];

function readFile() {
  const path = join(homeControl, 'secrets.json');
  if (!existsSync(path)) return {};
  try {
    return JSON.parse(readFileSync(path, 'utf8')).tuya ?? {};
  } catch (error) {
    throw new Error(`secrets.json is not valid JSON: ${error.message}`);
  }
}

const fromFile = readFile();
const tuya = Object.fromEntries(
  FIELDS.map(([key, envName]) => [key, process.env[envName] ?? fromFile[key] ?? '']),
);

const missing = FIELDS.map(([key]) => key).filter((key) => !tuya[key]);
if (missing.length) {
  console.warn(
    `\n  gen-secrets: no value for ${missing.join(', ')}.` +
      `\n  Copy secrets.example.json to home-control/secrets.json, or set the ROOM_TUYA_* env vars.` +
      `\n  Building anyway; AC control will report itself as unconfigured.\n`,
  );
}

const BANNER = 'Generated by scripts/gen-secrets.mjs. Do not edit; edit secrets.json instead.';
const q = (value) => JSON.stringify(value);

const outputs = [
  {
    path: join(homeControl, 'app', 'config.secrets.ts'),
    contents: `// ${BANNER}

export const TUYA_SECRETS = {
${FIELDS.map(([key]) => `  ${key}: ${q(tuya[key])},`).join('\n')}
} as const;
`,
  },
  {
    path: join(homeControl, 'ios', 'RoomWidgetShared', 'RoomSecrets.swift'),
    contents: swift(),
  },
  {
    path: join(repoRoot, 'room-widget-mac', 'Sources', 'Shared', 'RoomSecrets.swift'),
    contents: swift(),
  },
  {
    path: join(repoRoot, 'room-desktop', 'src', 'main', 'secrets.cjs'),
    contents: `// ${BANNER}

module.exports = {
  TUYA_SECRETS: {
${FIELDS.map(([key]) => `    ${key}: ${q(tuya[key])},`).join('\n')}
  },
};
`,
  },
];

function swift() {
  return `// ${BANNER}

import Foundation

enum RoomSecrets {
${FIELDS.map(([key]) => `  static let ${key} = ${q(tuya[key])}`).join('\n')}
}
`;
}

let written = 0;
for (const { path, contents } of outputs) {
  // The mac and desktop projects are absent on a build server that only
  // uploaded home-control, which is fine — skip rather than fail.
  if (!existsSync(dirname(dirname(path)))) continue;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  written += 1;
  console.log(`  gen-secrets: wrote ${path.replace(`${repoRoot}/`, '')}`);
}

console.log(`  gen-secrets: ${written} file(s) written.`);
